---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    author: intelliqit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appserver
  template:
    metadata:
      name: tomcat-pod
      labels:
        app: appserver
    spec:
      containers:
        - name: tomcat
          image: tomee
...
